In [155]:
#import libraries
import numpy as nm #numerical operations of multidimensional arrays or simply arrays
import matplotlib.pyplot as plt#graphical representation
import pandas as pd


In [156]:
#import datasets
data_set=pd.read_csv("suv_data.csv")
data_set.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [157]:
#extracting independent and dependent variable
x=data_set.iloc[:,[2,3]].values#.values means removing the heading and indexing(ie row numbers)
#[2,3]2nd and 3rd column,[2;3] 2 to 3-1=2 colomns ie 2nd column
y=data_set.iloc[:,4].values
#x
#y

In [158]:
#data_set.Age.mean()
#data_set.Age.var()

In [159]:
#!pip install scikit-learn

In [160]:
#splitting the datasetinto training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25,random_state=0) 

In [161]:
#feature scaling
from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)#fit and transform are functions in fit_transform function,
#which is in the class standard scalar()
x_test=st_x.fit_transform(x_test)

# KNN

In [162]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

# NotTraining occures in  a KNN model 
classifier1 = KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
classifier1.fit(x_train, y_train) #here fit means plotted the graph of points using training data x and y

KNeighborsClassifier()

In [163]:
y_pred = classifier1.predict(x_test)#we predict the y values for some x values.input given is x_test.then we get y pred.
#then we compare it with actual y test.here only 5 values are mipredicted
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [164]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [165]:
classifier1.score(x_test,y_test)*100 #or we can use accuracy_score(y_pred,y_test),parameters are different inside the brackets 

93.0

In [166]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_pred,y_test)*100

93.0

# SVM

In [167]:
from sklearn.svm import SVC #support vector classifier
classifier2 = SVC(kernel="linear" ,random_state =0)
classifier2.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [168]:
y_pred = classifier2.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [169]:
accuracy_score(y_pred,y_test)*100

88.0

In [170]:
classifier2.score(x_test,y_test)*100

88.0

In [171]:
from sklearn.tree import DecisionTreeClassifier
classifier3 =  DecisionTreeClassifier(criterion ="entropy",random_state =0)
classifier3.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [172]:
y_pred = classifier3.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [173]:
accuracy_score(y_pred,y_test)*100

90.0

# RandomForestClassifier

In [189]:
from sklearn.ensemble import RandomForestClassifier
classifier4 = RandomForestClassifier(n_estimators=10,criterion ="entropy")
classifier4.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [190]:
y_pred = classifier4.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [191]:
accuracy_score(y_pred,y_test)*100

93.0

# Naive Bayes Algorithm

In [192]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train,y_train)

GaussianNB()

In [193]:
y_pred = classifier5.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [194]:
accuracy_score(y_pred,y_test)*100

91.0